name: Teamwork Demo

on: [push]  

jobs:
  Test-GithubActions:
    runs-on: ubuntu-latest

    steps:
      - name: Automatically triggered test event
      - run: echo "Automatically triggered test event"

      - name: Print Teamwork Message
      - run: echo "Teamwork"

      - name: Print Group Members
      - run: echo "Group members: Vanessa and Winnie"

