name: Teamwork Demo
run-name: Testing Github Actions
on: [push]  
jobs:
  Test-GithubActions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Automatically triggered test event"
      - run: echo "Teamwork"
      - run: echo "Group members: Vanessa and Winnie"
      