name: Room 11 Demo
run-name: Testing Github Actions
on: [push]  
jobs:
  Test-GithubActions:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, world"
      - run: echo "Group members Vanessa Nassanga and Atim Winnie"

